import express from "express";
import { AddMovieToWatchList ,deleteMovieFromWatchList ,UpdateWatchListItem } from "../controller/watchList_controller.js";
import { AuthMiddleware } from "../middleware/AuthMiddleware.js";
import { validateRequestBody } from "../middleware/validateMiddleware.js";
import { AddWatchListSchema , UpdateWatchListItemSchema } from "../validator/watchlistVlidator.js";
const router = express.Router();
router.use(AuthMiddleware);
router.post("/", validateRequestBody(AddWatchListSchema), AddMovieToWatchList);
router.delete("/:id", deleteMovieFromWatchList);
router.put("/:id", validateRequestBody(UpdateWatchListItemSchema), UpdateWatchListItem);
export default router;